- name: Deploy to Tomcat
  hosts: localhost
  become: yes

  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "/var/lib/jenkins/workspace/MavenAnsibleWebApp1/target/MavenAnsibleWebApp1.war"
        dest: "/opt/tomcat/webapps/MavenAnsibleWebApp1.war"
        remote_src: no

    - name: Restart Tomcat
      systemd:
        name: tomcat10
        state: restarted
        


